include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true 
    prefer_relative_imports: true
    require_trailing_commas: true
    directives_ordering: true


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    todo: ignore