name: smart_house
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: "2.10.1"

dependencies:
  card_swiper: ^2.0.3
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_weather_bg_null_safety: ^1.0.0
  freezed_annotation: ^1.1.0
  go_router: ^3.0.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  lottie: ^1.2.2
  responsive_framework: ^0.1.7
  rxdart: ^0.27.3
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  test: ^1.19.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
