// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-c73YlYKWOFFWvu8-_t-KY80Y_1F5Zw',
    appId: '1:970095070276:web:223f10e0acde6944b90011',
    messagingSenderId: '970095070276',
    projectId: 'smart-house-e4368',
    authDomain: 'smart-house-e4368.firebaseapp.com',
    storageBucket: 'smart-house-e4368.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXkSALknLgbPgrqCdiss3JqGnA-xdyug',
    appId: '1:970095070276:android:f9b33707d5ebc729b90011',
    messagingSenderId: '970095070276',
    projectId: 'smart-house-e4368',
    storageBucket: 'smart-house-e4368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_Svlw8SZtrKdvYHt8DiJw10CtEtusM0',
    appId: '1:970095070276:ios:3e6802578a425516b90011',
    messagingSenderId: '970095070276',
    projectId: 'smart-house-e4368',
    storageBucket: 'smart-house-e4368.appspot.com',
    iosClientId:
        '970095070276-9b29jmem9j15gnc6rqo49o9p6jarabj4.apps.googleusercontent.com',
    iosBundleId: 'com.smart.app',
  );
}
